version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD", "echo", "stat", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  mesos-master:
    image: mesosphere/mesos-master:1.5.2
    container_name: mesos-master
    privileged: true
    environment:
      - MESOS_HOSTNAME=127.0.0.1  # Replace with $HOST_IP if available
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
      - MESOS_WORK_DIR=/tmp/mesos/work
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "5050:5050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mesos-slave:
    image: mesosphere/mesos-slave:1.5.2
    container_name: mesos-slave
    pid: "host"
    privileged: true
    environment:
      - MESOS_HOSTNAME=127.0.0.1  # Replace with $HOST_IP if available
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    depends_on:
      zookeeper:
        condition: service_healthy
      mesos-master:
        condition: service_healthy
    ports:
      - "5151:5151"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v1.11.7
    container_name: marathon
    command: >
      --master zk://zookeeper:2181/mesos
      --zk zk://zookeeper:2181/marathon
    environment:
      - PORT0=8080
    depends_on:
      zookeeper:
        condition: service_healthy
      mesos-master:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
